Change sass to css
biomejs/website pull request #1203
Opened 2024-09-24 05:12 UTC by mochi-sann

## Summary
fix #706

2024-09-25 08:51 UTC, ematipico commented
It seems there are regressions in the styles of the playground:
- https://biomejs.dev/playground/
- https://deploy-preview-1203--biomejs.netlify.app/playground/

2024-09-26 12:34 UTC, mochi-sann commented
@ematipico 
I have fixed the areas you pointed out, as well as other css problems.
Please review.

2024-09-27 18:54 UTC, ematipico commented
Are you sure @mochi-sann ? The deployed playground has still incorrect styles compared to production 🤔

2024-09-27 19:44 UTC, dyc3 requested changes
There are still some inaccurate conversions here.

2024-09-27 19:44 UTC, dyc3 commented on src/styles/playground/_diagnostics.css
| main | PR |
|------|----|
| ![image](https://github.com/user-attachments/assets/a46c093c-c04b-4b3e-b862-b810a532f611) | ![image](https://github.com/user-attachments/assets/35450bfa-2d6f-4a6e-a285-9b129ef39ead) |

2024-09-27 19:44 UTC, dyc3 commented on src/styles/playground/_settings.css
| main | PR |
|-|-|
| ![image](https://github.com/user-attachments/assets/1d775b3f-8b60-4549-940f-760f77206e29) | ![image](https://github.com/user-attachments/assets/cf6c644e-8f06-437c-9340-e1c22af6b53c) |

2024-09-27 19:44 UTC, dyc3 commented on src/pages/playground.astro
The background for the line numbers is different

| main | PR |
|-|-|
| ![image](https://github.com/user-attachments/assets/9b25572d-6736-461f-b315-66ae4d62b19f) | ![image](https://github.com/user-attachments/assets/d3ed7fc5-f7ee-4d2f-8688-23fe76681d5d) |

2024-09-27 19:44 UTC, dyc3 commented on src/pages/playground.astro
The background here too

| main | PR |
|-|-|
| ![image](https://github.com/user-attachments/assets/889aeac6-ef79-4ab4-9dca-431c5d4c95b9)| ![image](https://github.com/user-attachments/assets/9059ea98-b727-4928-9f03-b10eceedf5ee) |
| ![image](https://github.com/user-attachments/assets/21d0128e-6618-44e4-b04f-a25b0521b0d1) | ![image](https://github.com/user-attachments/assets/0eb56d1d-0c4e-4d31-a3ec-e089b7b97236) |

2024-10-01 06:43 UTC, mochi-sann commented
I have fixed the issue with the colors in the playground in dark mode. 
Please confirm

2024-10-01 15:17 UTC, mochi-sann commented on src/styles/playground/_settings.css
![image](https://github.com/user-attachments/assets/168a0b18-8f47-4640-96bd-ff27b2561322)
https://deploy-preview-1203--biomejs.netlify.app/playground/
The problem of checkboxes in the playground turning white in dark mode has been corrected so that checkboxes and other items turn black in dark mode, as shown in the image.

2024-10-01 15:21 UTC, dyc3 approved these changes

2024-10-02 08:53 UTC, ematipico approved these changes
Thank you @mochi-sann for your contribution! ❤️  I hope you had fun with this contribution :)

2024-10-02 09:51 UTC, merged